version: 2.1
jobs:   #Test SSH-fingerprints
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b5:79:dd:7b:4f:f2:8c:eb:a7:26:13:00:cb:5b:a9:18"]
      - run:  
          name: Install dependencies
          command: | #Install the dependencies
            apk add --update ansible  
      - run:
          name: Execute playbook
          command: |
            ansible-playbook main.yml -i inventory.txt

workflows:
  my_workflo:
    jobs:
      - configure_infrastructure
