version: 2.1
jobs:   #Test SSH-fingerprints
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["be:21:ae:6a:5e:7b:6f:ef:9b:cb:31:21:d4:69:93:bc"]
      - run:  
          name: Install dependencies
          command: | #Install the dependencies
            apk add --update ansible  
      - run:
          name: Execute playbook
          command: |
            ansible-playbook main.yml -i inventory.txt

    smoketest:
      - image: circleci/node:13.8.0
    steps:
       -run:
          name: Run Smoke Test
          command: |
            curl 34.220.2.77:3000

workflows:
  my_workflo:
    jobs:
      - configure_infrastructure
      - smoketest:
          requires:
           - smoketest

